name: Expo CI

on:
  push:
    branches-ignore: master

  pull_request:
    branches: master
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup to Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Run Tests
      run: |
        npm ci
        npx jest --ci
